name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: n8n-node-random/package-lock.json
        
    - name: Install dependencies
      working-directory: ./n8n-node-random
      run: npm ci
      
    - name: Run linting
      working-directory: ./n8n-node-random
      run: npm run lint
      
    - name: Run tests
      working-directory: ./n8n-node-random
      run: npm test
      
    - name: Build project
      working-directory: ./n8n-node-random
      run: npm run build